---

- name: "Ensure transmission-daemon is installed"
  package:
    name: transmission-daemon
    state: present

- name: Create the Transmission service config directory
  file:
    path: /etc/systemd/system/transmission-daemon.service.d
    state: directory
    owner: root
    group: root

- name: Configure Transmission service
  template:
    src: transmission-daemon-service-override.conf.j2
    dest: /etc/systemd/system/transmission-daemon.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: restart transmission

- name: Ensure transmission-daemon directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    recurse: yes
  with_items:
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"
    - "/etc/transmission-daemon"

- name: Stop transmission-daemon to create settings file
  service: 
    name: transmission-daemon
    state: stopped
  notify: restart transmission

- name: Ensure transmission-daemon settings file
  template:
    src: settings.json.j2
    dest: "/etc/transmission-daemon/settings.json"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0600
  notify: restart transmission

- name: Ensure Transmission autostarts
  service:
    name: transmission-daemon
    enabled: true
  notify: restart transmission

- name: Flush all handlers to ensure new config is loaded
  meta: flush_handlers

- name: Ensure Transmission is started
  service:
    name: transmission-daemon
    state: started
